// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.deephaven.proto.backplane.grpc.`object`

object ObjectProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    io.deephaven.proto.backplane.grpc.ticket.TicketProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      io.deephaven.proto.backplane.grpc.`object`.FetchObjectRequest,
      io.deephaven.proto.backplane.grpc.`object`.FetchObjectResponse,
      io.deephaven.proto.backplane.grpc.`object`.ConnectRequest,
      io.deephaven.proto.backplane.grpc.`object`.ClientData,
      io.deephaven.proto.backplane.grpc.`object`.ServerData,
      io.deephaven.proto.backplane.grpc.`object`.StreamRequest,
      io.deephaven.proto.backplane.grpc.`object`.StreamResponse,
      io.deephaven.proto.backplane.grpc.`object`.BrowserNextResponse
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CiFkZWVwaGF2ZW5fY29yZS9wcm90by9vYmplY3QucHJvdG8SIWlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYxohZ
  GVlcGhhdmVuX2NvcmUvcHJvdG8vdGlja2V0LnByb3RvInAKEkZldGNoT2JqZWN0UmVxdWVzdBJaCglzb3VyY2VfaWQYASABKAsyL
  i5pby5kZWVwaGF2ZW4ucHJvdG8uYmFja3BsYW5lLmdycGMuVHlwZWRUaWNrZXRCDeI/ChIIc291cmNlSWRSCHNvdXJjZUlkIsIBC
  hNGZXRjaE9iamVjdFJlc3BvbnNlEh0KBHR5cGUYASABKAlCCeI/BhIEdHlwZVIEdHlwZRIdCgRkYXRhGAIgASgMQgniPwYSBGRhd
  GFSBGRhdGESbQoQdHlwZWRfZXhwb3J0X2lkcxgDIAMoCzIuLmlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYy5UeXBlZ
  FRpY2tldEIT4j8QEg50eXBlZEV4cG9ydElkc1IOdHlwZWRFeHBvcnRJZHMibAoOQ29ubmVjdFJlcXVlc3QSWgoJc291cmNlX2lkG
  AEgASgLMi4uaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5ncnBjLlR5cGVkVGlja2V0Qg3iPwoSCHNvdXJjZUlkUghzb3VyY
  2VJZCKVAQoKQ2xpZW50RGF0YRImCgdwYXlsb2FkGAEgASgMQgziPwkSB3BheWxvYWRSB3BheWxvYWQSXwoKcmVmZXJlbmNlcxgCI
  AMoCzIuLmlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYy5UeXBlZFRpY2tldEIP4j8MEgpyZWZlcmVuY2VzUgpyZWZlc
  mVuY2VzIq4BCgpTZXJ2ZXJEYXRhEiYKB3BheWxvYWQYASABKAxCDOI/CRIHcGF5bG9hZFIHcGF5bG9hZBJ4ChNleHBvcnRlZF9yZ
  WZlcmVuY2VzGAIgAygLMi4uaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5ncnBjLlR5cGVkVGlja2V0QhfiPxQSEmV4cG9yd
  GVkUmVmZXJlbmNlc1ISZXhwb3J0ZWRSZWZlcmVuY2VzIscBCg1TdHJlYW1SZXF1ZXN0ElsKB2Nvbm5lY3QYASABKAsyMS5pby5kZ
  WVwaGF2ZW4ucHJvdG8uYmFja3BsYW5lLmdycGMuQ29ubmVjdFJlcXVlc3RCDOI/CRIHY29ubmVjdEgAUgdjb25uZWN0Ek4KBGRhd
  GEYAiABKAsyLS5pby5kZWVwaGF2ZW4ucHJvdG8uYmFja3BsYW5lLmdycGMuQ2xpZW50RGF0YUIJ4j8GEgRkYXRhSABSBGRhdGFCC
  QoHbWVzc2FnZSJrCg5TdHJlYW1SZXNwb25zZRJOCgRkYXRhGAEgASgLMi0uaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5nc
  nBjLlNlcnZlckRhdGFCCeI/BhIEZGF0YUgAUgRkYXRhQgkKB21lc3NhZ2UiFQoTQnJvd3Nlck5leHRSZXNwb25zZTKOBAoNT2JqZ
  WN0U2VydmljZRKBAQoLRmV0Y2hPYmplY3QSNS5pby5kZWVwaGF2ZW4ucHJvdG8uYmFja3BsYW5lLmdycGMuRmV0Y2hPYmplY3RSZ
  XF1ZXN0GjYuaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5ncnBjLkZldGNoT2JqZWN0UmVzcG9uc2UiA4gCARJ6Cg1NZXNzY
  WdlU3RyZWFtEjAuaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5ncnBjLlN0cmVhbVJlcXVlc3QaMS5pby5kZWVwaGF2ZW4uc
  HJvdG8uYmFja3BsYW5lLmdycGMuU3RyZWFtUmVzcG9uc2UiACgBMAESfAoRT3Blbk1lc3NhZ2VTdHJlYW0SMC5pby5kZWVwaGF2Z
  W4ucHJvdG8uYmFja3BsYW5lLmdycGMuU3RyZWFtUmVxdWVzdBoxLmlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYy5Td
  HJlYW1SZXNwb25zZSIAMAESfwoRTmV4dE1lc3NhZ2VTdHJlYW0SMC5pby5kZWVwaGF2ZW4ucHJvdG8uYmFja3BsYW5lLmdycGMuU
  3RyZWFtUmVxdWVzdBo2LmlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYy5Ccm93c2VyTmV4dFJlc3BvbnNlIgBCQkgBU
  AFaPGdpdGh1Yi5jb20vZGVlcGhhdmVuL2RlZXBoYXZlbi1jb3JlL2dvL2ludGVybmFsL3Byb3RvL29iamVjdGIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      io.deephaven.proto.backplane.grpc.ticket.TicketProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}