// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.deephaven.proto.backplane.grpc.config

object ConfigProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
      io.deephaven.proto.backplane.grpc.config.AuthenticationConstantsRequest,
      io.deephaven.proto.backplane.grpc.config.ConfigurationConstantsRequest,
      io.deephaven.proto.backplane.grpc.config.AuthenticationConstantsResponse,
      io.deephaven.proto.backplane.grpc.config.ConfigurationConstantsResponse,
      io.deephaven.proto.backplane.grpc.config.ConfigValue
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CiFkZWVwaGF2ZW5fY29yZS9wcm90by9jb25maWcucHJvdG8SIWlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYyIgC
  h5BdXRoZW50aWNhdGlvbkNvbnN0YW50c1JlcXVlc3QiHwodQ29uZmlndXJhdGlvbkNvbnN0YW50c1JlcXVlc3QiuAIKH0F1dGhlb
  nRpY2F0aW9uQ29uc3RhbnRzUmVzcG9uc2USjAEKDWNvbmZpZ192YWx1ZXMYASADKAsyVC5pby5kZWVwaGF2ZW4ucHJvdG8uYmFja
  3BsYW5lLmdycGMuQXV0aGVudGljYXRpb25Db25zdGFudHNSZXNwb25zZS5Db25maWdWYWx1ZXNFbnRyeUIR4j8OEgxjb25maWdWY
  Wx1ZXNSDGNvbmZpZ1ZhbHVlcxqFAQoRQ29uZmlnVmFsdWVzRW50cnkSGgoDa2V5GAEgASgJQgjiPwUSA2tleVIDa2V5ElAKBXZhb
  HVlGAIgASgLMi4uaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5ncnBjLkNvbmZpZ1ZhbHVlQgriPwcSBXZhbHVlUgV2YWx1Z
  ToCOAEitgIKHkNvbmZpZ3VyYXRpb25Db25zdGFudHNSZXNwb25zZRKLAQoNY29uZmlnX3ZhbHVlcxgBIAMoCzJTLmlvLmRlZXBoY
  XZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYy5Db25maWd1cmF0aW9uQ29uc3RhbnRzUmVzcG9uc2UuQ29uZmlnVmFsdWVzRW50cnlCE
  eI/DhIMY29uZmlnVmFsdWVzUgxjb25maWdWYWx1ZXMahQEKEUNvbmZpZ1ZhbHVlc0VudHJ5EhoKA2tleRgBIAEoCUII4j8FEgNrZ
  XlSA2tleRJQCgV2YWx1ZRgCIAEoCzIuLmlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYy5Db25maWdWYWx1ZUIK4j8HE
  gV2YWx1ZVIFdmFsdWU6AjgBIkwKC0NvbmZpZ1ZhbHVlEjUKDHN0cmluZ192YWx1ZRgDIAEoCUIQ4j8NEgtzdHJpbmdWYWx1ZUgAU
  gtzdHJpbmdWYWx1ZUIGCgRraW5kMtwCCg1Db25maWdTZXJ2aWNlEqUBChpHZXRBdXRoZW50aWNhdGlvbkNvbnN0YW50cxJBLmlvL
  mRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYy5BdXRoZW50aWNhdGlvbkNvbnN0YW50c1JlcXVlc3QaQi5pby5kZWVwaGF2Z
  W4ucHJvdG8uYmFja3BsYW5lLmdycGMuQXV0aGVudGljYXRpb25Db25zdGFudHNSZXNwb25zZSIAEqIBChlHZXRDb25maWd1cmF0a
  W9uQ29uc3RhbnRzEkAuaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5ncnBjLkNvbmZpZ3VyYXRpb25Db25zdGFudHNSZXF1Z
  XN0GkEuaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5ncnBjLkNvbmZpZ3VyYXRpb25Db25zdGFudHNSZXNwb25zZSIAQkJIA
  VABWjxnaXRodWIuY29tL2RlZXBoYXZlbi9kZWVwaGF2ZW4tY29yZS9nby9pbnRlcm5hbC9wcm90by9jb25maWdiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}