// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.deephaven.proto.backplane.grpc.application

object ApplicationProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    io.deephaven.proto.backplane.grpc.ticket.TicketProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      io.deephaven.proto.backplane.grpc.application.ListFieldsRequest,
      io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate,
      io.deephaven.proto.backplane.grpc.application.FieldInfo
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CiZkZWVwaGF2ZW5fY29yZS9wcm90by9hcHBsaWNhdGlvbi5wcm90bxIhaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5nc
  nBjGiFkZWVwaGF2ZW5fY29yZS9wcm90by90aWNrZXQucHJvdG8iEwoRTGlzdEZpZWxkc1JlcXVlc3QilgIKEkZpZWxkc0NoYW5nZ
  VVwZGF0ZRJUCgdjcmVhdGVkGAEgAygLMiwuaW8uZGVlcGhhdmVuLnByb3RvLmJhY2twbGFuZS5ncnBjLkZpZWxkSW5mb0IM4j8JE
  gdjcmVhdGVkUgdjcmVhdGVkElQKB3VwZGF0ZWQYAiADKAsyLC5pby5kZWVwaGF2ZW4ucHJvdG8uYmFja3BsYW5lLmdycGMuRmllb
  GRJbmZvQgziPwkSB3VwZGF0ZWRSB3VwZGF0ZWQSVAoHcmVtb3ZlZBgDIAMoCzIsLmlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhb
  mUuZ3JwYy5GaWVsZEluZm9CDOI/CRIHcmVtb3ZlZFIHcmVtb3ZlZCLfAgoJRmllbGRJbmZvEmMKDHR5cGVkX3RpY2tldBgBIAEoC
  zIuLmlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYy5UeXBlZFRpY2tldEIQ4j8NEgt0eXBlZFRpY2tldFILdHlwZWRUa
  WNrZXQSLQoKZmllbGRfbmFtZRgCIAEoCUIO4j8LEglmaWVsZE5hbWVSCWZpZWxkTmFtZRJCChFmaWVsZF9kZXNjcmlwdGlvbhgDI
  AEoCUIV4j8SEhBmaWVsZERlc2NyaXB0aW9uUhBmaWVsZERlc2NyaXB0aW9uEj8KEGFwcGxpY2F0aW9uX25hbWUYBCABKAlCFOI/E
  RIPYXBwbGljYXRpb25OYW1lUg9hcHBsaWNhdGlvbk5hbWUSOQoOYXBwbGljYXRpb25faWQYBSABKAlCEuI/DxINYXBwbGljYXRpb
  25JZFINYXBwbGljYXRpb25JZDKTAQoSQXBwbGljYXRpb25TZXJ2aWNlEn0KCkxpc3RGaWVsZHMSNC5pby5kZWVwaGF2ZW4ucHJvd
  G8uYmFja3BsYW5lLmdycGMuTGlzdEZpZWxkc1JlcXVlc3QaNS5pby5kZWVwaGF2ZW4ucHJvdG8uYmFja3BsYW5lLmdycGMuRmllb
  GRzQ2hhbmdlVXBkYXRlIgAwAUJHSAFQAVpBZ2l0aHViLmNvbS9kZWVwaGF2ZW4vZGVlcGhhdmVuLWNvcmUvZ28vaW50ZXJuYWwvc
  HJvdG8vYXBwbGljYXRpb25iBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      io.deephaven.proto.backplane.grpc.ticket.TicketProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}