// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.deephaven.proto.backplane.script.grpc.console

@SerialVersionUID(0L)
final case class DocumentRange(
    start: _root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position] = _root_.scala.None,
    end: _root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[DocumentRange] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (start.isDefined) {
        val __value = start.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (end.isDefined) {
        val __value = end.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      start.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      end.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getStart: io.deephaven.proto.backplane.script.grpc.console.Position = start.getOrElse(io.deephaven.proto.backplane.script.grpc.console.Position.defaultInstance)
    def clearStart: DocumentRange = copy(start = _root_.scala.None)
    def withStart(__v: io.deephaven.proto.backplane.script.grpc.console.Position): DocumentRange = copy(start = Option(__v))
    def getEnd: io.deephaven.proto.backplane.script.grpc.console.Position = end.getOrElse(io.deephaven.proto.backplane.script.grpc.console.Position.defaultInstance)
    def clearEnd: DocumentRange = copy(end = _root_.scala.None)
    def withEnd(__v: io.deephaven.proto.backplane.script.grpc.console.Position): DocumentRange = copy(end = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => start.orNull
        case 2 => end.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => start.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => end.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.deephaven.proto.backplane.script.grpc.console.DocumentRange.type = io.deephaven.proto.backplane.script.grpc.console.DocumentRange
    // @@protoc_insertion_point(GeneratedMessage[io.deephaven.proto.backplane.script.grpc.DocumentRange])
}

object DocumentRange extends scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.script.grpc.console.DocumentRange] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.script.grpc.console.DocumentRange] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.deephaven.proto.backplane.script.grpc.console.DocumentRange = {
    var __start: _root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position] = _root_.scala.None
    var __end: _root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __start = _root_.scala.Option(__start.fold(_root_.scalapb.LiteParser.readMessage[io.deephaven.proto.backplane.script.grpc.console.Position](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __end = _root_.scala.Option(__end.fold(_root_.scalapb.LiteParser.readMessage[io.deephaven.proto.backplane.script.grpc.console.Position](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.deephaven.proto.backplane.script.grpc.console.DocumentRange(
        start = __start,
        end = __end,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.deephaven.proto.backplane.script.grpc.console.DocumentRange] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.deephaven.proto.backplane.script.grpc.console.DocumentRange(
        start = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position]]),
        end = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = io.deephaven.proto.backplane.script.grpc.console.ConsoleProto.javaDescriptor.getMessageTypes().get(23)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = io.deephaven.proto.backplane.script.grpc.console.ConsoleProto.scalaDescriptor.messages(23)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = io.deephaven.proto.backplane.script.grpc.console.Position
      case 2 => __out = io.deephaven.proto.backplane.script.grpc.console.Position
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = io.deephaven.proto.backplane.script.grpc.console.DocumentRange(
    start = _root_.scala.None,
    end = _root_.scala.None
  )
  implicit class DocumentRangeLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.script.grpc.console.DocumentRange]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.deephaven.proto.backplane.script.grpc.console.DocumentRange](_l) {
    def start: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.script.grpc.console.Position] = field(_.getStart)((c_, f_) => c_.copy(start = _root_.scala.Option(f_)))
    def optionalStart: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position]] = field(_.start)((c_, f_) => c_.copy(start = f_))
    def end: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.script.grpc.console.Position] = field(_.getEnd)((c_, f_) => c_.copy(end = _root_.scala.Option(f_)))
    def optionalEnd: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position]] = field(_.end)((c_, f_) => c_.copy(end = f_))
  }
  final val START_FIELD_NUMBER = 1
  final val END_FIELD_NUMBER = 2
  def of(
    start: _root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position],
    end: _root_.scala.Option[io.deephaven.proto.backplane.script.grpc.console.Position]
  ): _root_.io.deephaven.proto.backplane.script.grpc.console.DocumentRange = _root_.io.deephaven.proto.backplane.script.grpc.console.DocumentRange(
    start,
    end
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[io.deephaven.proto.backplane.script.grpc.DocumentRange])
}
