// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.deephaven.proto.backplane.script.grpc.console

@SerialVersionUID(0L)
final case class ExecuteCommandResponse(
    errorMessage: _root_.scala.Predef.String = "",
    changes: _root_.scala.Option[io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ExecuteCommandResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = errorMessage
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      if (changes.isDefined) {
        val __value = changes.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = errorMessage
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      changes.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withErrorMessage(__v: _root_.scala.Predef.String): ExecuteCommandResponse = copy(errorMessage = __v)
    def getChanges: io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate = changes.getOrElse(io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate.defaultInstance)
    def clearChanges: ExecuteCommandResponse = copy(changes = _root_.scala.None)
    def withChanges(__v: io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate): ExecuteCommandResponse = copy(changes = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = errorMessage
          if (__t != "") __t else null
        }
        case 2 => changes.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(errorMessage)
        case 2 => changes.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse.type = io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse
    // @@protoc_insertion_point(GeneratedMessage[io.deephaven.proto.backplane.script.grpc.ExecuteCommandResponse])
}

object ExecuteCommandResponse extends scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse = {
    var __errorMessage: _root_.scala.Predef.String = ""
    var __changes: _root_.scala.Option[io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __errorMessage = _input__.readStringRequireUtf8()
        case 18 =>
          __changes = _root_.scala.Option(__changes.fold(_root_.scalapb.LiteParser.readMessage[io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse(
        errorMessage = __errorMessage,
        changes = __changes,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse(
        errorMessage = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        changes = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = io.deephaven.proto.backplane.script.grpc.console.ConsoleProto.javaDescriptor.getMessageTypes().get(9)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = io.deephaven.proto.backplane.script.grpc.console.ConsoleProto.scalaDescriptor.messages(9)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse(
    errorMessage = "",
    changes = _root_.scala.None
  )
  implicit class ExecuteCommandResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse](_l) {
    def errorMessage: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.errorMessage)((c_, f_) => c_.copy(errorMessage = f_))
    def changes: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate] = field(_.getChanges)((c_, f_) => c_.copy(changes = _root_.scala.Option(f_)))
    def optionalChanges: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate]] = field(_.changes)((c_, f_) => c_.copy(changes = f_))
  }
  final val ERROR_MESSAGE_FIELD_NUMBER = 1
  final val CHANGES_FIELD_NUMBER = 2
  def of(
    errorMessage: _root_.scala.Predef.String,
    changes: _root_.scala.Option[io.deephaven.proto.backplane.grpc.application.FieldsChangeUpdate]
  ): _root_.io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse = _root_.io.deephaven.proto.backplane.script.grpc.console.ExecuteCommandResponse(
    errorMessage,
    changes
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[io.deephaven.proto.backplane.script.grpc.ExecuteCommandResponse])
}
