// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.deephaven.proto.backplane.grpc.ticket

object TicketProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
      io.deephaven.proto.backplane.grpc.ticket.Ticket,
      io.deephaven.proto.backplane.grpc.ticket.TypedTicket
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CiFkZWVwaGF2ZW5fY29yZS9wcm90by90aWNrZXQucHJvdG8SIWlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYyItC
  gZUaWNrZXQSIwoGdGlja2V0GAEgASgMQgviPwgSBnRpY2tldFIGdGlja2V0InwKC1R5cGVkVGlja2V0Ek4KBnRpY2tldBgBIAEoC
  zIpLmlvLmRlZXBoYXZlbi5wcm90by5iYWNrcGxhbmUuZ3JwYy5UaWNrZXRCC+I/CBIGdGlja2V0UgZ0aWNrZXQSHQoEdHlwZRgCI
  AEoCUIJ4j8GEgR0eXBlUgR0eXBlQkJIAVABWjxnaXRodWIuY29tL2RlZXBoYXZlbi9kZWVwaGF2ZW4tY29yZS9nby9pbnRlcm5hb
  C9wcm90by90aWNrZXRiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}