// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.deephaven.proto.backplane.grpc.table

@SerialVersionUID(0L)
final case class MatchesCondition(
    reference: _root_.scala.Option[io.deephaven.proto.backplane.grpc.table.Reference] = _root_.scala.None,
    regex: _root_.scala.Predef.String = "",
    caseSensitivity: io.deephaven.proto.backplane.grpc.table.CaseSensitivity = io.deephaven.proto.backplane.grpc.table.CaseSensitivity.MATCH_CASE,
    matchType: io.deephaven.proto.backplane.grpc.table.MatchType = io.deephaven.proto.backplane.grpc.table.MatchType.REGULAR,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[MatchesCondition] {
    @transient
    private var __serializedSizeMemoized: _root_.scala.Int = 0
    private def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (reference.isDefined) {
        val __value = reference.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = regex
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = caseSensitivity.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(3, __value)
        }
      };
      
      {
        val __value = matchType.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(4, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      reference.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = regex
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = caseSensitivity.value
        if (__v != 0) {
          _output__.writeEnum(3, __v)
        }
      };
      {
        val __v = matchType.value
        if (__v != 0) {
          _output__.writeEnum(4, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def getReference: io.deephaven.proto.backplane.grpc.table.Reference = reference.getOrElse(io.deephaven.proto.backplane.grpc.table.Reference.defaultInstance)
    def clearReference: MatchesCondition = copy(reference = _root_.scala.None)
    def withReference(__v: io.deephaven.proto.backplane.grpc.table.Reference): MatchesCondition = copy(reference = Option(__v))
    def withRegex(__v: _root_.scala.Predef.String): MatchesCondition = copy(regex = __v)
    def withCaseSensitivity(__v: io.deephaven.proto.backplane.grpc.table.CaseSensitivity): MatchesCondition = copy(caseSensitivity = __v)
    def withMatchType(__v: io.deephaven.proto.backplane.grpc.table.MatchType): MatchesCondition = copy(matchType = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => reference.orNull
        case 2 => {
          val __t = regex
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = caseSensitivity.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 4 => {
          val __t = matchType.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => reference.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => _root_.scalapb.descriptors.PString(regex)
        case 3 => _root_.scalapb.descriptors.PEnum(caseSensitivity.scalaValueDescriptor)
        case 4 => _root_.scalapb.descriptors.PEnum(matchType.scalaValueDescriptor)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.deephaven.proto.backplane.grpc.table.MatchesCondition.type = io.deephaven.proto.backplane.grpc.table.MatchesCondition
    // @@protoc_insertion_point(GeneratedMessage[io.deephaven.proto.backplane.grpc.MatchesCondition])
}

object MatchesCondition extends scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.grpc.table.MatchesCondition] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.grpc.table.MatchesCondition] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.deephaven.proto.backplane.grpc.table.MatchesCondition = {
    var __reference: _root_.scala.Option[io.deephaven.proto.backplane.grpc.table.Reference] = _root_.scala.None
    var __regex: _root_.scala.Predef.String = ""
    var __caseSensitivity: io.deephaven.proto.backplane.grpc.table.CaseSensitivity = io.deephaven.proto.backplane.grpc.table.CaseSensitivity.MATCH_CASE
    var __matchType: io.deephaven.proto.backplane.grpc.table.MatchType = io.deephaven.proto.backplane.grpc.table.MatchType.REGULAR
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __reference = _root_.scala.Option(__reference.fold(_root_.scalapb.LiteParser.readMessage[io.deephaven.proto.backplane.grpc.table.Reference](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __regex = _input__.readStringRequireUtf8()
        case 24 =>
          __caseSensitivity = io.deephaven.proto.backplane.grpc.table.CaseSensitivity.fromValue(_input__.readEnum())
        case 32 =>
          __matchType = io.deephaven.proto.backplane.grpc.table.MatchType.fromValue(_input__.readEnum())
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.deephaven.proto.backplane.grpc.table.MatchesCondition(
        reference = __reference,
        regex = __regex,
        caseSensitivity = __caseSensitivity,
        matchType = __matchType,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.deephaven.proto.backplane.grpc.table.MatchesCondition] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.deephaven.proto.backplane.grpc.table.MatchesCondition(
        reference = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[io.deephaven.proto.backplane.grpc.table.Reference]]),
        regex = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        caseSensitivity = io.deephaven.proto.backplane.grpc.table.CaseSensitivity.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(io.deephaven.proto.backplane.grpc.table.CaseSensitivity.MATCH_CASE.scalaValueDescriptor).number),
        matchType = io.deephaven.proto.backplane.grpc.table.MatchType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(io.deephaven.proto.backplane.grpc.table.MatchType.REGULAR.scalaValueDescriptor).number)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TableProto.javaDescriptor.getMessageTypes().get(54)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TableProto.scalaDescriptor.messages(54)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = io.deephaven.proto.backplane.grpc.table.Reference
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 3 => io.deephaven.proto.backplane.grpc.table.CaseSensitivity
      case 4 => io.deephaven.proto.backplane.grpc.table.MatchType
    }
  }
  lazy val defaultInstance = io.deephaven.proto.backplane.grpc.table.MatchesCondition(
    reference = _root_.scala.None,
    regex = "",
    caseSensitivity = io.deephaven.proto.backplane.grpc.table.CaseSensitivity.MATCH_CASE,
    matchType = io.deephaven.proto.backplane.grpc.table.MatchType.REGULAR
  )
  implicit class MatchesConditionLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.grpc.table.MatchesCondition]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.deephaven.proto.backplane.grpc.table.MatchesCondition](_l) {
    def reference: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.grpc.table.Reference] = field(_.getReference)((c_, f_) => c_.copy(reference = _root_.scala.Option(f_)))
    def optionalReference: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[io.deephaven.proto.backplane.grpc.table.Reference]] = field(_.reference)((c_, f_) => c_.copy(reference = f_))
    def regex: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.regex)((c_, f_) => c_.copy(regex = f_))
    def caseSensitivity: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.grpc.table.CaseSensitivity] = field(_.caseSensitivity)((c_, f_) => c_.copy(caseSensitivity = f_))
    def matchType: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.grpc.table.MatchType] = field(_.matchType)((c_, f_) => c_.copy(matchType = f_))
  }
  final val REFERENCE_FIELD_NUMBER = 1
  final val REGEX_FIELD_NUMBER = 2
  final val CASE_SENSITIVITY_FIELD_NUMBER = 3
  final val MATCH_TYPE_FIELD_NUMBER = 4
  def of(
    reference: _root_.scala.Option[io.deephaven.proto.backplane.grpc.table.Reference],
    regex: _root_.scala.Predef.String,
    caseSensitivity: io.deephaven.proto.backplane.grpc.table.CaseSensitivity,
    matchType: io.deephaven.proto.backplane.grpc.table.MatchType
  ): _root_.io.deephaven.proto.backplane.grpc.table.MatchesCondition = _root_.io.deephaven.proto.backplane.grpc.table.MatchesCondition(
    reference,
    regex,
    caseSensitivity,
    matchType
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[io.deephaven.proto.backplane.grpc.MatchesCondition])
}
