// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.deephaven.proto.backplane.grpc.storage

sealed abstract class ItemType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = io.deephaven.proto.backplane.grpc.storage.ItemType
  type RecognizedType = io.deephaven.proto.backplane.grpc.storage.ItemType.Recognized
  def isUnknown: _root_.scala.Boolean = false
  def isDirectory: _root_.scala.Boolean = false
  def isFile: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[ItemType] = io.deephaven.proto.backplane.grpc.storage.ItemType
  final def asRecognized: _root_.scala.Option[io.deephaven.proto.backplane.grpc.storage.ItemType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[io.deephaven.proto.backplane.grpc.storage.ItemType.Recognized])
}

object ItemType extends _root_.scalapb.GeneratedEnumCompanion[ItemType] {
  sealed trait Recognized extends ItemType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ItemType] = this
  
  /** Should not be used, exists only to indicate that this was left unset
    */
  @SerialVersionUID(0L)
  case object UNKNOWN extends ItemType(0) with ItemType.Recognized {
    val index = 0
    val name = "UNKNOWN"
    override def isUnknown: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DIRECTORY extends ItemType(1) with ItemType.Recognized {
    val index = 1
    val name = "DIRECTORY"
    override def isDirectory: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object FILE extends ItemType(2) with ItemType.Recognized {
    val index = 2
    val name = "FILE"
    override def isFile: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends ItemType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(UNKNOWN, DIRECTORY, FILE)
  def fromValue(__value: _root_.scala.Int): ItemType = __value match {
    case 0 => UNKNOWN
    case 1 => DIRECTORY
    case 2 => FILE
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = io.deephaven.proto.backplane.grpc.storage.StorageProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = io.deephaven.proto.backplane.grpc.storage.StorageProto.scalaDescriptor.enums(0)
}