// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.deephaven.proto.backplane.grpc.storage

/** @param items
  *   List of items found in the specified directory.
  * @param canonicalPath
  *   The canonical path of the listed directory. This is useful to recognize the basename
  *   of the items in a cross-platform way.
  */
@SerialVersionUID(0L)
final case class ListItemsResponse(
    items: _root_.scala.Seq[io.deephaven.proto.backplane.grpc.storage.ItemInfo] = _root_.scala.Seq.empty,
    canonicalPath: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ListItemsResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      items.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = canonicalPath
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      items.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = canonicalPath
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def clearItems = copy(items = _root_.scala.Seq.empty)
    def addItems(__vs: io.deephaven.proto.backplane.grpc.storage.ItemInfo *): ListItemsResponse = addAllItems(__vs)
    def addAllItems(__vs: Iterable[io.deephaven.proto.backplane.grpc.storage.ItemInfo]): ListItemsResponse = copy(items = items ++ __vs)
    def withItems(__v: _root_.scala.Seq[io.deephaven.proto.backplane.grpc.storage.ItemInfo]): ListItemsResponse = copy(items = __v)
    def withCanonicalPath(__v: _root_.scala.Predef.String): ListItemsResponse = copy(canonicalPath = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => items
        case 2 => {
          val __t = canonicalPath
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(items.iterator.map(_.toPMessage).toVector)
        case 2 => _root_.scalapb.descriptors.PString(canonicalPath)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.deephaven.proto.backplane.grpc.storage.ListItemsResponse.type = io.deephaven.proto.backplane.grpc.storage.ListItemsResponse
    // @@protoc_insertion_point(GeneratedMessage[io.deephaven.proto.backplane.grpc.ListItemsResponse])
}

object ListItemsResponse extends scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.grpc.storage.ListItemsResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.grpc.storage.ListItemsResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.deephaven.proto.backplane.grpc.storage.ListItemsResponse = {
    val __items: _root_.scala.collection.immutable.VectorBuilder[io.deephaven.proto.backplane.grpc.storage.ItemInfo] = new _root_.scala.collection.immutable.VectorBuilder[io.deephaven.proto.backplane.grpc.storage.ItemInfo]
    var __canonicalPath: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __items += _root_.scalapb.LiteParser.readMessage[io.deephaven.proto.backplane.grpc.storage.ItemInfo](_input__)
        case 18 =>
          __canonicalPath = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.deephaven.proto.backplane.grpc.storage.ListItemsResponse(
        items = __items.result(),
        canonicalPath = __canonicalPath,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.deephaven.proto.backplane.grpc.storage.ListItemsResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.deephaven.proto.backplane.grpc.storage.ListItemsResponse(
        items = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[io.deephaven.proto.backplane.grpc.storage.ItemInfo]]).getOrElse(_root_.scala.Seq.empty),
        canonicalPath = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = io.deephaven.proto.backplane.grpc.storage.StorageProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = io.deephaven.proto.backplane.grpc.storage.StorageProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = io.deephaven.proto.backplane.grpc.storage.ItemInfo
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = io.deephaven.proto.backplane.grpc.storage.ListItemsResponse(
    items = _root_.scala.Seq.empty,
    canonicalPath = ""
  )
  implicit class ListItemsResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.grpc.storage.ListItemsResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.deephaven.proto.backplane.grpc.storage.ListItemsResponse](_l) {
    def items: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[io.deephaven.proto.backplane.grpc.storage.ItemInfo]] = field(_.items)((c_, f_) => c_.copy(items = f_))
    def canonicalPath: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.canonicalPath)((c_, f_) => c_.copy(canonicalPath = f_))
  }
  final val ITEMS_FIELD_NUMBER = 1
  final val CANONICAL_PATH_FIELD_NUMBER = 2
  def of(
    items: _root_.scala.Seq[io.deephaven.proto.backplane.grpc.storage.ItemInfo],
    canonicalPath: _root_.scala.Predef.String
  ): _root_.io.deephaven.proto.backplane.grpc.storage.ListItemsResponse = _root_.io.deephaven.proto.backplane.grpc.storage.ListItemsResponse(
    items,
    canonicalPath
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[io.deephaven.proto.backplane.grpc.ListItemsResponse])
}
