// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.deephaven.proto.backplane.grpc.storage

/** Requests to move a file to a new path, which may be in a different directory. Presently it is not
  * permitted to overwrite an existing file in this way.
  *
  * @param oldPath
  *   The path where the file currently exists
  * @param newPath
  *   The path where the file should be moved to
  * @param allowOverwrite
  *   True to permit replacing an existing file, false to require that no file already exists with that name.
  */
@SerialVersionUID(0L)
final case class MoveItemRequest(
    oldPath: _root_.scala.Predef.String = "",
    newPath: _root_.scala.Predef.String = "",
    allowOverwrite: _root_.scala.Boolean = false,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[MoveItemRequest] {
    @transient
    private var __serializedSizeMemoized: _root_.scala.Int = 0
    private def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = oldPath
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = newPath
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = allowOverwrite
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = oldPath
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = newPath
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = allowOverwrite
        if (__v != false) {
          _output__.writeBool(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withOldPath(__v: _root_.scala.Predef.String): MoveItemRequest = copy(oldPath = __v)
    def withNewPath(__v: _root_.scala.Predef.String): MoveItemRequest = copy(newPath = __v)
    def withAllowOverwrite(__v: _root_.scala.Boolean): MoveItemRequest = copy(allowOverwrite = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = oldPath
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = newPath
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = allowOverwrite
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(oldPath)
        case 2 => _root_.scalapb.descriptors.PString(newPath)
        case 3 => _root_.scalapb.descriptors.PBoolean(allowOverwrite)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.deephaven.proto.backplane.grpc.storage.MoveItemRequest.type = io.deephaven.proto.backplane.grpc.storage.MoveItemRequest
    // @@protoc_insertion_point(GeneratedMessage[io.deephaven.proto.backplane.grpc.MoveItemRequest])
}

object MoveItemRequest extends scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.grpc.storage.MoveItemRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.deephaven.proto.backplane.grpc.storage.MoveItemRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.deephaven.proto.backplane.grpc.storage.MoveItemRequest = {
    var __oldPath: _root_.scala.Predef.String = ""
    var __newPath: _root_.scala.Predef.String = ""
    var __allowOverwrite: _root_.scala.Boolean = false
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __oldPath = _input__.readStringRequireUtf8()
        case 18 =>
          __newPath = _input__.readStringRequireUtf8()
        case 24 =>
          __allowOverwrite = _input__.readBool()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.deephaven.proto.backplane.grpc.storage.MoveItemRequest(
        oldPath = __oldPath,
        newPath = __newPath,
        allowOverwrite = __allowOverwrite,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.deephaven.proto.backplane.grpc.storage.MoveItemRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.deephaven.proto.backplane.grpc.storage.MoveItemRequest(
        oldPath = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        newPath = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        allowOverwrite = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = StorageProto.javaDescriptor.getMessageTypes().get(7)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = StorageProto.scalaDescriptor.messages(7)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = io.deephaven.proto.backplane.grpc.storage.MoveItemRequest(
    oldPath = "",
    newPath = "",
    allowOverwrite = false
  )
  implicit class MoveItemRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.deephaven.proto.backplane.grpc.storage.MoveItemRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.deephaven.proto.backplane.grpc.storage.MoveItemRequest](_l) {
    def oldPath: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.oldPath)((c_, f_) => c_.copy(oldPath = f_))
    def newPath: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.newPath)((c_, f_) => c_.copy(newPath = f_))
    def allowOverwrite: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.allowOverwrite)((c_, f_) => c_.copy(allowOverwrite = f_))
  }
  final val OLD_PATH_FIELD_NUMBER = 1
  final val NEW_PATH_FIELD_NUMBER = 2
  final val ALLOW_OVERWRITE_FIELD_NUMBER = 3
  def of(
    oldPath: _root_.scala.Predef.String,
    newPath: _root_.scala.Predef.String,
    allowOverwrite: _root_.scala.Boolean
  ): _root_.io.deephaven.proto.backplane.grpc.storage.MoveItemRequest = _root_.io.deephaven.proto.backplane.grpc.storage.MoveItemRequest(
    oldPath,
    newPath,
    allowOverwrite
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[io.deephaven.proto.backplane.grpc.MoveItemRequest])
}
